### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brettz9** [josegaert/ext-mathjax#6]
Hi,

We are bundling your extension in svgedit. However, I'd like to clearly label the licenses in use, and with your extension listed as "Apache", I'm curious if this is, as I expect "Apache-2.0"?

Thanks!
Brett

**Comment by josegaert** [comment]
Dear Brett,
That is nice to hear!
I unfortunately didn't maintain this project for all these years. And so I also don't know anymore why I choose Apache.
But please, slap any open source license on it that simplifies your life. MIT, GPL
Greetings,
Jo

**Comment by brettz9** [comment]
Great, thanks!
